version: '3'
services:
  api:
    container_name: api
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    networks:
      - nfl-app-network
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./api:/app/
      - nodemodules:/app/node_modules

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - "api:be"
    networks:
      - nfl-app-network

  mongo:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - nfl-app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  nfl-app-network:
    driver: bridge
volumes:
  nodemodules:
  dbdata: