version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - "backend:be"